### ISSUE TITLE
Request to remove SLibSettings

### ISSUE THREAD

**Issue by mkh-user** [Subject-Team/Subject-Library#13]
I've noticed that some people want to remove SLibSettings and its features, this would overshadow the default parameters.
If you agree with removing SLibSettings, state your reason and give your suggestion about the default parameters. use 👍 for this comment
if you want to keep SLibSettings, write your reasons. use 👎 for this comment

If there is no consensus, the issue will be closed in 3 days

**Comment by mkh-user** [comment]
**Keep** [1] 

> Please use this format to organize your comments:
> **Keep** [kepp comment number]
> **Remove** [remove comment number]

I think we should keep the default parameters.
In this case, if we remove SLibSettings, we need to move them to SLib.gd, so there are two ways:
In the first method, the user should change the desired values ​​using SLib.Default_MergeUnigue = true, in this case we will have more lines in each project.
In the second method, the user enters the SLib.gd file and sets his needs there, this method is a bit complicated and editing the library file may cause problems in its operation.
That's why I think SLibSettings is a better idea.

**Comment by snipercup** [comment]
I will disagree with removing slibsettings, but maybe we can change the format. Let's have SLibSettings be a resource that the user can customize in the editor. SLib can then reference this resource and read from it.

**Comment by mkh-user** [comment]
Conclusion:
- Remove SLibSettings
- Create SLibConfig plugin
- Move SLibSettings to editor project settings
